### ISSUE TITLE
Implement support for Provider / Consumer node execution type

### ISSUE THREAD

**Issue by vade** [Fabric-Project/Fabric#57]
Today we rely on `isDirty` flag and custom overrides to determine if a node needs execution

While this "works", semantically its unclear and could break some contracts down the line.

We need to update GraphRenderer to

* gather all provider nodes, and execute them once
* gather all consumer nodes, and execute them recursively climbing through the graph to nab connected processors

I think this is correct, given that we now can have subgraphs with just a provider, with no consumer to pull it?

**Comment by tobyspark** [comment]
In QC, provider patches are purple, which vs. black vs. blue is nice UX. 

But right now I’m wondering if is there actually a technical need? Is the rationale that a provider patch needs the execute method tickled, to do the work on their outside sources? If so, is that good design – a provider node should be able to do whatever work it needs outside of the Fabric execution cycle, and the result be there on demand?

**Comment by vade** [comment]
Well, its not so much outside of the execution cycle, its more for edge case where there is no consumer to trigger a pull, (imagine a subgraph with publish ports)

In some scenarios theres a chance providers dont get executed. 

Theres no method for providers to be executed outside of the graph render execution being called (or any node), the facility is there for providers to be executed regardless of graph connectivity, which is a requirement (this allows them to be tickled so to speak, regardless of a need for any other node to consume its output)

Yea, UI should get tweaked too.

**Comment by vade** [comment]
Fixed in #55

**Comment by tobyspark** [comment]
I still don’t get why being executed a requirement, if a node's output isn’t going anywhere? i.e. without pull from a consumer. A subgraph with publish ports is still being pulled (or is disconnected) from that published port?

If the need is to produce a value on cue, then isn’t a processor node sufficient? If the need is to enable some background process that allows the output to be supplied, then yes we need some kind of provider type but invoking execute every frame doesn’t seem a good pattern for that? Instead a provider node having an `enabled` input port would seem to be a better fit? i.e. that’s an event to start some kind of subprocess, and then an event to stop it.

...feel free to ignore this as you plough on. Just stood out to me. And I’m quite likely missing something.

**Comment by vade** [comment]
Depending on the type of node, or what its external service, hardware etc its connected to, there could be a need to service that connection on occasion, which is why theres the time base Idle time mode. 

I think (and i could be wrong?) that idle time mode consumers and producers need servicing occasionally, determined by the next time they vend from the older QC API that supports the idle time mode.
